-- Oracle Cloud ADB에서 테이블 존재 여부 확인

-- 1. USER_ITEMS 테이블 확인
SELECT TABLE_NAME, NUM_ROWS, LAST_ANALYZED
FROM USER_TABLES
WHERE TABLE_NAME = 'USER_ITEMS';

-- 2. SHOP_ITEMS 테이블 확인
SELECT TABLE_NAME, NUM_ROWS, LAST_ANALYZED
FROM USER_TABLES
WHERE TABLE_NAME = 'SHOP_ITEMS';

-- 3. 모든 SHOP 관련 테이블 목록 확인
SELECT TABLE_NAME
FROM USER_TABLES
WHERE TABLE_NAME LIKE '%SHOP%' OR TABLE_NAME LIKE '%ITEM%' OR TABLE_NAME LIKE '%USER_ITEM%'
ORDER BY TABLE_NAME;

-- 4. 대소문자 구분 없이 테이블 확인 (Oracle은 대문자로 저장되지만 확인용)
SELECT TABLE_NAME
FROM USER_TABLES
WHERE UPPER(TABLE_NAME) IN ('USER_ITEMS', 'SHOP_ITEMS', 'BANNER_STICKERS', 'PURCHASE_HISTORY', 'TOKEN_TRANSACTIONS')
ORDER BY TABLE_NAME;

-- 5. 만약 테이블이 없으면 생성 스크립트 실행 필요
-- CREATE_SHOP_TABLES_COMPLETE.sql 파일의 내용을 실행해야 합니다.

