-- Oracle 데이터베이스 USERS 테이블 구조 확인
-- 이 SQL을 실행해서 어떤 컬럼들이 NOT NULL인지 확인하세요

SELECT COLUMN_NAME, DATA_TYPE, NULLABLE, DATA_DEFAULT
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'USERS'
ORDER BY COLUMN_ID;

-- 또는 더 자세한 정보
SELECT * FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'USERS';

