-- Oracle SEQUENCE 생성 스크립트
-- 이 파일을 Oracle SQL Developer 또는 다른 클라이언트에서 실행하세요

-- 기존 SEQUENCE 삭제 (선택사항, 처음에는 에러가 나와도 무시해도 됨)
DROP SEQUENCE USERS_SEQ;
DROP SEQUENCE POSTS_SEQ;
DROP SEQUENCE COMMENTS_SEQ;
DROP SEQUENCE BETS_SEQ;
DROP SEQUENCE BET_VOTES_SEQ;
DROP SEQUENCE BET_SETTLEMENTS_SEQ;
DROP SEQUENCE POST_REACTION_SEQ;

-- SEQUENCE 생성
CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE POSTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE COMMENTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE BETS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE BET_VOTES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE BET_SETTLEMENTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE POST_REACTION_SEQ START WITH 1 INCREMENT BY 1;

-- SEQUENCE 확인
SELECT SEQUENCE_NAME FROM USER_SEQUENCES WHERE SEQUENCE_NAME LIKE '%_SEQ';

