-- USER_ITEMS 테이블만 생성 (Oracle Cloud ADB에서 실행)

-- 기존 테이블이 있으면 삭제 (주의: 데이터가 모두 삭제됩니다)
-- DROP TABLE USER_ITEMS CASCADE CONSTRAINTS;

-- USER_ITEMS 테이블 생성
CREATE TABLE USER_ITEMS (
    ID NUMBER PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    SHOP_ITEM_ID NUMBER NOT NULL,
    QUANTITY NUMBER NOT NULL,
    IS_EQUIPPED NUMBER(1,0),
    PURCHASED_AT TIMESTAMP,
    CONSTRAINT FK_USER_ITEMS_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_USER_ITEMS_SHOP_ITEM FOREIGN KEY (SHOP_ITEM_ID) REFERENCES SHOP_ITEMS(ID),
    CONSTRAINT UK_USER_ITEMS_USER_SHOP UNIQUE (USER_ID, SHOP_ITEM_ID)
);

-- DEFAULT 값은 ALTER TABLE로 추가하거나 애플리케이션에서 처리
-- 필요시 아래 주석 해제:
-- ALTER TABLE USER_ITEMS MODIFY (QUANTITY DEFAULT 1);
-- ALTER TABLE USER_ITEMS MODIFY (IS_EQUIPPED DEFAULT 0);
-- ALTER TABLE USER_ITEMS MODIFY (PURCHASED_AT DEFAULT CURRENT_TIMESTAMP);

-- 시퀀스 생성 (이미 있으면 에러 무시)
BEGIN
    EXECUTE IMMEDIATE 'CREATE SEQUENCE USER_ITEMS_SEQ START WITH 1 INCREMENT BY 1';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE = -955 THEN NULL; -- 이미 존재함
        ELSE RAISE;
        END IF;
END;
/

-- 인덱스 생성
CREATE INDEX IDX_USER_ITEMS_USER_ID ON USER_ITEMS(USER_ID);
CREATE INDEX IDX_USER_ITEMS_SHOP_ITEM_ID ON USER_ITEMS(SHOP_ITEM_ID);

-- 테이블 생성 확인
SELECT 'USER_ITEMS 테이블 생성 완료' AS STATUS FROM DUAL;

SELECT TABLE_NAME 
FROM USER_TABLES 
WHERE TABLE_NAME = 'USER_ITEMS';

