-- POST_MEDIA 시퀀스 생성
CREATE SEQUENCE POST_MEDIA_SEQ
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- POST_MEDIA 테이블 생성
CREATE TABLE POST_MEDIA (
    ID NUMBER NOT NULL,
    POST_ID NUMBER NOT NULL,
    FILE_URL VARCHAR2(500) NOT NULL,
    FILE_NAME VARCHAR2(255) NOT NULL,
    ORIGINAL_FILE_NAME VARCHAR2(255),
    FILE_TYPE VARCHAR2(50) NOT NULL,
    CONTENT_TYPE VARCHAR2(100),
    FILE_SIZE NUMBER,
    CREATED_AT TIMESTAMP,
    CONSTRAINT POST_MEDIA_PK PRIMARY KEY (ID),
    CONSTRAINT POST_MEDIA_FK FOREIGN KEY (POST_ID) REFERENCES POSTS(ID) ON DELETE CASCADE
);

-- 인덱스 생성 (성능 향상)
CREATE INDEX IDX_POST_MEDIA_POST_ID ON POST_MEDIA(POST_ID);

-- 코멘트 추가
COMMENT ON TABLE POST_MEDIA IS '게시글 첨부 미디어 테이블';
COMMENT ON COLUMN POST_MEDIA.ID IS '미디어 ID (PK)';
COMMENT ON COLUMN POST_MEDIA.POST_ID IS '게시글 ID (FK)';
COMMENT ON COLUMN POST_MEDIA.FILE_URL IS '파일 접근 URL (예: /api/files/filename.jpg)';
COMMENT ON COLUMN POST_MEDIA.FILE_NAME IS '서버에 저장된 파일명 (UUID + 확장자)';
COMMENT ON COLUMN POST_MEDIA.ORIGINAL_FILE_NAME IS '사용자가 업로드한 원본 파일명';
COMMENT ON COLUMN POST_MEDIA.FILE_TYPE IS '파일 타입 (image, video)';
COMMENT ON COLUMN POST_MEDIA.CONTENT_TYPE IS 'MIME 타입 (예: image/jpeg, video/mp4)';
COMMENT ON COLUMN POST_MEDIA.FILE_SIZE IS '파일 크기 (바이트)';
COMMENT ON COLUMN POST_MEDIA.CREATED_AT IS '업로드 시간';

