-- COMMENTS 테이블 정리: 불필요한 컬럼 제거

-- 1. 현재 컬럼 확인
SELECT COLUMN_NAME, DATA_TYPE, NULLABLE
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'COMMENTS'
ORDER BY COLUMN_ID;

-- 2. 불필요한 컬럼들 제거 (컬럼이 존재하는 경우에만)
ALTER TABLE COMMENTS DROP COLUMN USER_ID;  -- AUTHOR_ID와 중복
ALTER TABLE COMMENTS DROP COLUMN UPDATED_AT; -- 댓글 수정 기능 없음
ALTER TABLE COMMENTS DROP COLUMN PARENT_ID;  -- 대댓글 기능 없음

-- 3. LIKES, DISLIKES로 통일 (컬럼이 안 맞다면)
-- ALTER TABLE COMMENTS RENAME COLUMN LIKE_COUNT TO LIKES;
-- ALTER TABLE COMMENTS RENAME COLUMN DISLIKE_COUNT TO DISLIKES;

-- 최종 필요한 컬럼:
-- ID, POST_ID, AUTHOR_ID, CONTENT, LIKES, DISLIKES, CREATED_AT, IS_DELETED

