-- Oracle SEQUENCE 생성 스크립트
-- 애플리케이션 시작 시 자동으로 실행

BEGIN
   EXECUTE IMMEDIATE 'CREATE SEQUENCE USERS_SEQ START WITH 1 INCREMENT BY 1';
EXCEPTION
   WHEN OTHERS THEN NULL;  -- 이미 존재하면 무시
END;
/

BEGIN
   EXECUTE IMMEDIATE 'CREATE SEQUENCE POSTS_SEQ START WITH 1 INCREMENT BY 1';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'CREATE SEQUENCE COMMENTS_SEQ START WITH 1 INCREMENT BY 1';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'CREATE SEQUENCE BETS_SEQ START WITH 1 INCREMENT BY 1';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'CREATE SEQUENCE BET_VOTES_SEQ START WITH 1 INCREMENT BY 1';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'CREATE SEQUENCE BET_SETTLEMENTS_SEQ START WITH 1 INCREMENT BY 1';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'CREATE SEQUENCE POST_REACTION_SEQ START WITH 1 INCREMENT BY 1';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

