-- POSTS 테이블에 WRITER_B와 CONTENT_B 컬럼 추가
-- 롤문철 카테고리에서 작성자B 닉네임과 본문을 저장하기 위한 컬럼

-- WRITER_B 컬럼 추가 (작성자B 닉네임)
ALTER TABLE POSTS 
ADD WRITER_B VARCHAR2(100);

-- CONTENT_B 컬럼 추가 (작성자B 본문)
ALTER TABLE POSTS 
ADD CONTENT_B CLOB;

-- 컬럼 추가 완료 확인
SELECT COLUMN_NAME, DATA_TYPE, DATA_LENGTH, NULLABLE 
FROM USER_TAB_COLUMNS 
WHERE TABLE_NAME = 'POSTS' 
AND COLUMN_NAME IN ('WRITER_B', 'CONTENT_B');

