-- ============================================
-- 로그인 문제 진단 SQL
-- ============================================

-- 1. USERS 테이블 확인
SELECT 
    'USERS 테이블 상태' AS CHECK_TYPE,
    CASE 
        WHEN COUNT(*) > 0 THEN '존재함'
        ELSE '없음 - 문제 원인!'
    END AS STATUS
FROM USER_TABLES 
WHERE TABLE_NAME = 'USERS';

-- 2. USERS 테이블 구조 확인
SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    DATA_LENGTH,
    NULLABLE,
    DATA_DEFAULT
FROM USER_TAB_COLUMNS
WHERE TABLE_NAME = 'USERS'
ORDER BY COLUMN_ID;

-- 3. USERS 테이블 데이터 확인 (개수만)
SELECT 
    'USERS 테이블 데이터 개수' AS CHECK_TYPE,
    COUNT(*) AS USER_COUNT
FROM USERS;

-- 4. USERS 테이블에 사용자 있는지 확인 (username, email만)
SELECT 
    ID,
    USERNAME,
    EMAIL,
    CASE 
        WHEN PASSWORD_HASH IS NULL THEN '비밀번호 없음'
        WHEN LENGTH(PASSWORD_HASH) < 10 THEN '비밀번호 이상'
        ELSE '정상'
    END AS PASSWORD_STATUS,
    ROLE,
    TOKEN_BALANCE
FROM USERS
ORDER BY CREATED_AT DESC;

-- 5. USERS_SEQ 시퀀스 확인
SELECT 
    'USERS_SEQ 시퀀스 상태' AS CHECK_TYPE,
    CASE 
        WHEN COUNT(*) > 0 THEN '존재함'
        ELSE '없음 - 문제 원인!'
    END AS STATUS
FROM USER_SEQUENCES 
WHERE SEQUENCE_NAME = 'USERS_SEQ';

-- 6. BETS 관련 외래키가 USERS에 영향을 주는지 확인
SELECT 
    CONSTRAINT_NAME,
    TABLE_NAME,
    CONSTRAINT_TYPE,
    STATUS
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_TYPE = 'R' 
  AND (TABLE_NAME LIKE 'BET%' OR TABLE_NAME = 'BETS')
  AND R_CONSTRAINT_NAME IN (
      SELECT CONSTRAINT_NAME 
      FROM USER_CONSTRAINTS 
      WHERE TABLE_NAME = 'USERS' AND CONSTRAINT_TYPE = 'P'
  );

-- 7. 모든 외래키 제약조건 확인
SELECT 
    TABLE_NAME,
    CONSTRAINT_NAME,
    CONSTRAINT_TYPE,
    STATUS,
    SEARCH_CONDITION
FROM USER_CONSTRAINTS
WHERE CONSTRAINT_TYPE IN ('R', 'C', 'U', 'P')
ORDER BY TABLE_NAME, CONSTRAINT_TYPE;

