-- ============================================
-- 내기(Bet) 관련 테이블 생성 SQL (간단 버전)
-- 외래키 없이 테이블만 먼저 생성
-- ============================================

-- 기존 테이블 삭제
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BET_SETTLEMENTS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BET_VOTES CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BETS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- 시퀀스 삭제
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE BET_SETTLEMENTS_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE BET_VOTES_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE BETS_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- ============================================
-- 1. BETS 테이블 (외래키 없이 생성)
-- ============================================
CREATE TABLE BETS (
    ID NUMBER PRIMARY KEY,
    POST_ID NUMBER NOT NULL,
    BETTOR_A_ID NUMBER NOT NULL,
    BETTOR_B_ID NUMBER NOT NULL,
    BET_TITLE VARCHAR2(200) NOT NULL,
    OPTION_A VARCHAR2(100) NOT NULL,
    OPTION_B VARCHAR2(100) NOT NULL,
    DEADLINE TIMESTAMP NOT NULL,
    TOTAL_VOTES NUMBER DEFAULT 0 NOT NULL,
    VOTES_FOR_A NUMBER DEFAULT 0 NOT NULL,
    VOTES_FOR_B NUMBER DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- 2. BET_VOTES 테이블
-- ============================================
CREATE TABLE BET_VOTES (
    ID NUMBER PRIMARY KEY,
    BET_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    SELECTED_OPTION VARCHAR2(1) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- 3. BET_SETTLEMENTS 테이블
-- ============================================
CREATE TABLE BET_SETTLEMENTS (
    ID NUMBER PRIMARY KEY,
    BET_ID NUMBER NOT NULL,
    WINNER_OPTION VARCHAR2(1) NOT NULL,
    SETTLED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ============================================
-- 제약조건 추가
-- ============================================

-- BETS 테이블 제약조건
ALTER TABLE BETS ADD CONSTRAINT UK_BETS_POST_ID UNIQUE (POST_ID);
ALTER TABLE BETS ADD CONSTRAINT CK_BETS_OPTIONS CHECK (TOTAL_VOTES >= 0 AND VOTES_FOR_A >= 0 AND VOTES_FOR_B >= 0);

-- BET_VOTES 테이블 제약조건
ALTER TABLE BET_VOTES ADD CONSTRAINT CK_BET_VOTES_OPTION CHECK (SELECTED_OPTION IN ('A', 'B'));
ALTER TABLE BET_VOTES ADD CONSTRAINT UK_BET_VOTES_USER_BET UNIQUE (BET_ID, USER_ID);

-- BET_SETTLEMENTS 테이블 제약조건
ALTER TABLE BET_SETTLEMENTS ADD CONSTRAINT UK_BET_SETTLEMENTS_BET_ID UNIQUE (BET_ID);
ALTER TABLE BET_SETTLEMENTS ADD CONSTRAINT CK_BET_SETTLEMENTS_OPTION CHECK (WINNER_OPTION IN ('A', 'B'));

-- ============================================
-- 외래키 추가 (POSTS와 USERS가 있는 경우만)
-- ============================================

-- POSTS 테이블이 있으면 외래키 추가
BEGIN
    IF (SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'POSTS') > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE BETS ADD CONSTRAINT FK_BETS_POST FOREIGN KEY (POST_ID) REFERENCES POSTS(ID)';
        DBMS_OUTPUT.PUT_LINE('FK_BETS_POST 외래키 추가됨');
    ELSE
        DBMS_OUTPUT.PUT_LINE('POSTS 테이블이 없어 FK_BETS_POST 외래키 추가 안 함');
    END IF;
END;
/

-- USERS 테이블이 있으면 외래키 추가
BEGIN
    IF (SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'USERS') > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE BETS ADD CONSTRAINT FK_BETS_BETTOR_A FOREIGN KEY (BETTOR_A_ID) REFERENCES USERS(ID)';
        EXECUTE IMMEDIATE 'ALTER TABLE BETS ADD CONSTRAINT FK_BETS_BETTOR_B FOREIGN KEY (BETTOR_B_ID) REFERENCES USERS(ID)';
        DBMS_OUTPUT.PUT_LINE('FK_BETS_BETTOR_A, FK_BETS_BETTOR_B 외래키 추가됨');
    ELSE
        DBMS_OUTPUT.PUT_LINE('USERS 테이블이 없어 외래키 추가 안 함');
    END IF;
END;
/

-- BETS 테이블이 있으면 BET_VOTES 외래키 추가
BEGIN
    IF (SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'BETS') > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE BET_VOTES ADD CONSTRAINT FK_BET_VOTES_BET FOREIGN KEY (BET_ID) REFERENCES BETS(ID)';
        DBMS_OUTPUT.PUT_LINE('FK_BET_VOTES_BET 외래키 추가됨');
    END IF;
    
    IF (SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'USERS') > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE BET_VOTES ADD CONSTRAINT FK_BET_VOTES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID)';
        DBMS_OUTPUT.PUT_LINE('FK_BET_VOTES_USER 외래키 추가됨');
    END IF;
END;
/

-- BETS 테이블이 있으면 BET_SETTLEMENTS 외래키 추가
BEGIN
    IF (SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = 'BETS') > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE BET_SETTLEMENTS ADD CONSTRAINT FK_BET_SETTLEMENTS_BET FOREIGN KEY (BET_ID) REFERENCES BETS(ID)';
        DBMS_OUTPUT.PUT_LINE('FK_BET_SETTLEMENTS_BET 외래키 추가됨');
    END IF;
END;
/

-- ============================================
-- 시퀀스 생성
-- ============================================
CREATE SEQUENCE BETS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE BET_VOTES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE BET_SETTLEMENTS_SEQ START WITH 1 INCREMENT BY 1;

-- ============================================
-- 인덱스 생성
-- ============================================
CREATE INDEX IDX_BETS_POST_ID ON BETS(POST_ID);
CREATE INDEX IDX_BETS_BETTOR_A_ID ON BETS(BETTOR_A_ID);
CREATE INDEX IDX_BETS_BETTOR_B_ID ON BETS(BETTOR_B_ID);
CREATE INDEX IDX_BETS_DEADLINE ON BETS(DEADLINE);
CREATE INDEX IDX_BET_VOTES_BET_ID ON BET_VOTES(BET_ID);
CREATE INDEX IDX_BET_VOTES_USER_ID ON BET_VOTES(USER_ID);
CREATE INDEX IDX_BET_SETTLEMENTS_BET_ID ON BET_SETTLEMENTS(BET_ID);

-- ============================================
-- 확인
-- ============================================
SELECT 'Bets tables created successfully' AS STATUS FROM DUAL;

SELECT TABLE_NAME 
FROM USER_TABLES 
WHERE TABLE_NAME IN ('BETS', 'BET_VOTES', 'BET_SETTLEMENTS')
ORDER BY TABLE_NAME;

