-- ============================================
-- 내기(Bet) 관련 테이블 전체 생성 SQL (Oracle)
-- Oracle Cloud ADB에서 실행
-- 기존 테이블/시퀀스/인덱스가 있으면 자동으로 삭제 후 재생성합니다
-- 
-- 필수 조건:
-- 1. POSTS 테이블이 먼저 생성되어 있어야 합니다
-- 2. USERS 테이블이 먼저 생성되어 있어야 합니다
--
-- 실행 전 CHECK_REQUIRED_TABLES.sql로 확인하세요
-- ============================================

-- 필수 테이블 확인
DECLARE
    v_posts_count NUMBER;
    v_users_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_posts_count FROM USER_TABLES WHERE TABLE_NAME = 'POSTS';
    SELECT COUNT(*) INTO v_users_count FROM USER_TABLES WHERE TABLE_NAME = 'USERS';
    
    IF v_posts_count = 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'POSTS 테이블이 없습니다. 먼저 POSTS 테이블을 생성하세요.');
    END IF;
    
    IF v_users_count = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'USERS 테이블이 없습니다. 먼저 USERS 테이블을 생성하세요.');
    END IF;
    
    DBMS_OUTPUT.PUT_LINE('필수 테이블 확인 완료: POSTS, USERS');
END;
/

-- 기존 테이블 및 시퀀스 삭제 (오류 무시)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BET_SETTLEMENTS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BET_VOTES CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE BETS CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE BET_SETTLEMENTS_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE BET_VOTES_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE BETS_SEQ';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- ============================================
-- 1. BETS 테이블 (내기 정보)
-- ============================================
CREATE TABLE BETS (
    ID NUMBER PRIMARY KEY,
    POST_ID NUMBER NOT NULL,
    BETTOR_A_ID NUMBER NOT NULL,
    BETTOR_B_ID NUMBER NOT NULL,
    BET_TITLE VARCHAR2(200) NOT NULL,
    OPTION_A VARCHAR2(100) NOT NULL,
    OPTION_B VARCHAR2(100) NOT NULL,
    DEADLINE TIMESTAMP NOT NULL,
    TOTAL_VOTES NUMBER DEFAULT 0 NOT NULL,
    VOTES_FOR_A NUMBER DEFAULT 0 NOT NULL,
    VOTES_FOR_B NUMBER DEFAULT 0 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- UNIQUE 제약조건 추가
ALTER TABLE BETS ADD CONSTRAINT UK_BETS_POST_ID UNIQUE (POST_ID);

-- 외래키 제약조건 추가
ALTER TABLE BETS ADD CONSTRAINT FK_BETS_POST FOREIGN KEY (POST_ID) REFERENCES POSTS(ID);
ALTER TABLE BETS ADD CONSTRAINT FK_BETS_BETTOR_A FOREIGN KEY (BETTOR_A_ID) REFERENCES USERS(ID);
ALTER TABLE BETS ADD CONSTRAINT FK_BETS_BETTOR_B FOREIGN KEY (BETTOR_B_ID) REFERENCES USERS(ID);

-- ============================================
-- 2. BET_VOTES 테이블 (내기 투표 기록)
-- ============================================
CREATE TABLE BET_VOTES (
    ID NUMBER PRIMARY KEY,
    BET_ID NUMBER NOT NULL,
    USER_ID NUMBER NOT NULL,
    SELECTED_OPTION VARCHAR2(1) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_BET_VOTES_BET FOREIGN KEY (BET_ID) REFERENCES BETS(ID),
    CONSTRAINT FK_BET_VOTES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT CK_BET_VOTES_OPTION CHECK (SELECTED_OPTION IN ('A', 'B')),
    CONSTRAINT UK_BET_VOTES_USER_BET UNIQUE (BET_ID, USER_ID)
);

-- ============================================
-- 3. BET_SETTLEMENTS 테이블 (내기 정산 기록)
-- ============================================
CREATE TABLE BET_SETTLEMENTS (
    ID NUMBER PRIMARY KEY,
    BET_ID NUMBER NOT NULL UNIQUE,
    WINNER_OPTION VARCHAR2(1) NOT NULL,
    SETTLED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_BET_SETTLEMENTS_BET FOREIGN KEY (BET_ID) REFERENCES BETS(ID),
    CONSTRAINT CK_BET_SETTLEMENTS_OPTION CHECK (WINNER_OPTION IN ('A', 'B'))
);

-- ============================================
-- 시퀀스 생성
-- ============================================
CREATE SEQUENCE BETS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE BET_VOTES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE BET_SETTLEMENTS_SEQ START WITH 1 INCREMENT BY 1;

-- ============================================
-- 인덱스 생성 (성능 최적화)
-- ============================================
-- 기존 인덱스 삭제 (오류 무시)
BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IDX_BETS_POST_ID';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IDX_BETS_BETTOR_A_ID';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IDX_BETS_BETTOR_B_ID';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IDX_BETS_DEADLINE';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IDX_BET_VOTES_BET_ID';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IDX_BET_VOTES_USER_ID';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX IDX_BET_SETTLEMENTS_BET_ID';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- 인덱스 생성
CREATE INDEX IDX_BETS_POST_ID ON BETS(POST_ID);
CREATE INDEX IDX_BETS_BETTOR_A_ID ON BETS(BETTOR_A_ID);
CREATE INDEX IDX_BETS_BETTOR_B_ID ON BETS(BETTOR_B_ID);
CREATE INDEX IDX_BETS_DEADLINE ON BETS(DEADLINE);
CREATE INDEX IDX_BET_VOTES_BET_ID ON BET_VOTES(BET_ID);
CREATE INDEX IDX_BET_VOTES_USER_ID ON BET_VOTES(USER_ID);
CREATE INDEX IDX_BET_SETTLEMENTS_BET_ID ON BET_SETTLEMENTS(BET_ID);

-- ============================================
-- 확인 쿼리
-- ============================================

-- 테이블 생성 확인
SELECT 'Bets tables created successfully' AS STATUS FROM DUAL;

-- 테이블 목록 확인
SELECT TABLE_NAME 
FROM USER_TABLES 
WHERE TABLE_NAME IN (
    'BETS', 'BET_VOTES', 'BET_SETTLEMENTS'
)
ORDER BY TABLE_NAME;

-- 시퀀스 목록 확인
SELECT SEQUENCE_NAME 
FROM USER_SEQUENCES 
WHERE SEQUENCE_NAME IN (
    'BETS_SEQ', 'BET_VOTES_SEQ', 'BET_SETTLEMENTS_SEQ'
)
ORDER BY SEQUENCE_NAME;

